language: node_js
sudo: required

services:
  - docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t sxw1212/sammauldin .;
    docker tag sxw1212/sammauldin us.gcr.io/wombo-combo-95420/sammauldin;
    docker login -e 1234@5678.com -u _json_key -p "$DOCKER_PASSWORD" https://us.gcr.io;
    docker push us.gcr.io/wombo-combo-95420/sammauldin;
    fi

node_js:
- '7'

notifications:
  email: false
